# -*- coding: utf-8 -*-
"""Copy of gemini_api_workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19n6AO7qp3nxqu_jpr3yN8rPdJwMKhrbN

<a href="https://colab.research.google.com/github/linhkid/gdg-others/blob/main/gemini_api_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 A Tour of the Gemini API — Hands-on Workshop

This notebook walks you through the key capabilities of the **Gemini API** as covered in the presentation.  
Each section is self-contained — run the cells top-to-bottom within each section.

**Sections:**
1. Setup & Installation
2. Basic Text Generation (Gemini 3)
3. Tools & Agents
   - Google Search Grounding
   - URL Context
   - Google Maps Grounding
   - Code Execution
   - Function Calling
   - File Search (RAG)
4. GenMedia — Image Generation (Nano Banana)
5. Audio & Speech (TTS)
6. Live API (Streaming)

---

## 1. Setup & Installation

### Get your API key
1. Visit [Google AI Studio](https://aistudio.google.com)
2. Click **Get API key**
3. Copy it and paste below
"""

# Install the Google GenAI SDK
!pip install -q google-genai Pillow
!pip install -q google-adk

import os
from google import genai
from google.colab import userdata
from google.genai import types

# ============================
# 👇 PASTE YOUR API KEY HERE
# ============================
#GOOGLE_API_KEY = "YOUR_API_KEY_HERE"

# You can also set it via environment variable:
#export GOOGLE_API_KEY="your-key"
#GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
client = genai.Client(api_key=GOOGLE_API_KEY)
print("✅ Client initialized successfully!")

"""---
## 2. Basic Text Generation — Gemini 3

Gemini 3 represents the shift to an **era of action**:  
- Gemini 1 → Understanding  
- Gemini 2 → Thinking  
- Gemini 3 → **Action**

Available models:
- `gemini-3-pro-preview` — Most capable
- `gemini-3-flash-preview` — Fast & efficient
"""

# --- Simple text generation with Gemini 3 Flash ---

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="How does AI work? Explain in 3 sentences."
)
print(response.text)

# --- Gemini 3.1 Pro — More powerful reasoning ---

response = client.models.generate_content(
    model="gemini-3.1-pro-preview",
    contents="What are the implications of quantum computing on current encryption standards?"
)
print(response.text)

"""### 2.1 New API Features — Thinking Level

Control the model's internal reasoning with `thinking_level`: `high` or `low`.
"""

# --- Thinking level control ---

# High thinking — deeper reasoning
response_high = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="Solve step-by-step: If a train leaves at 9am going 60mph, and another at 10am going 90mph, when does the second catch up?",
    config=types.GenerateContentConfig(
        thinking_config=types.ThinkingConfig(thinking_level="HIGH")
    )
)

# Print thinking and response
for part in response_high.candidates[0].content.parts:
    if part.thought:
        print("💭 THINKING:", part.text[:300], "...\n")
    else:
        print("📝 RESPONSE:", part.text)

"""---
## 3. Tools & Agents

Gemini models support powerful tool integrations:
- **Google Search** — Real-time web grounding
- **URL Context** — Extract content from web pages
- **Google Maps** — Location-aware responses
- **Code Execution** — Run Python in the model
- **Function Calling** — Connect to your own APIs
- **File Search** — RAG over your documents

### 3.1 Google Search Grounding

Connect Gemini to real-time web content for factual, up-to-date answers with citations.
"""

# --- Google Search grounding ---

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="What are the latest AI news this week?",
    config=types.GenerateContentConfig(
        tools=[types.Tool(google_search=types.GoogleSearch())]
    )
)

print(response.text)

# Print grounding metadata if available
if response.candidates[0].grounding_metadata:
    metadata = response.candidates[0].grounding_metadata
    if metadata.search_entry_point:
        print("\n🔗 Search query:", metadata.search_entry_point.rendered_content[:200] if metadata.search_entry_point.rendered_content else "N/A")

"""### 3.2 URL Context

Natively extract and process content from user-provided web page URLs.
"""

# --- URL Context: Extract & compare web content ---

url1 = "https://blog.google/technology/ai/"

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents=f"Summarize the latest posts from this blog: {url1}",
    config=types.GenerateContentConfig(
        tools=[types.Tool(url_context=types.UrlContext())]
    )
)

print(response.text)

# --- URL Context: Compare two web pages ---

url1 = "https://en.wikipedia.org/wiki/Python_(programming_language)"
url2 = "https://en.wikipedia.org/wiki/Rust_(programming_language)"

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents=f"Compare the key features and use cases of Python vs Rust based on these pages: {url1} and {url2}",
    config=types.GenerateContentConfig(
        tools=[types.Tool(url_context=types.UrlContext())]
    )
)

print(response.text)

"""### 3.3 Google Maps Grounding

Connect Gemini with Google Maps for location-aware, factually accurate responses.
"""

# --- Google Maps grounding ---

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="What are the best Italian restaurants within a 15-minute walk from here?",
    config=types.GenerateContentConfig(
        tools=[types.Tool(google_maps=types.GoogleMaps())],
        tool_config=types.ToolConfig(
            retrieval_config=types.RetrievalConfig(
                lat_lng=types.LatLng(
                    latitude=21.0285,   # Hanoi — change to your location!
                    longitude=105.8542
                )
            )
        ),
    )
)

print(response.text)

"""### 3.4 Code Execution

Enable the model to generate **and run** Python code server-side.
"""

# --- Code Execution: Let Gemini write & run Python ---

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="What is the sum of the first 50 prime numbers? Write and run the code.",
    config=types.GenerateContentConfig(
        tools=[types.Tool(code_execution=types.ToolCodeExecution())]
    )
)

# Display all parts (code + output + text)
for part in response.candidates[0].content.parts:
    if part.executable_code:
        print("💻 CODE:")
        print(part.executable_code.code)
        print()
    elif part.code_execution_result:
        print("📊 OUTPUT:")
        print(part.code_execution_result.output)
        print()
    elif part.text:
        print("📝 TEXT:")
        print(part.text)
        print()

# --- Code Execution: Data analysis ---

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="""Generate sample sales data for 12 months, then:
1. Calculate monthly growth rates
2. Find the best and worst months
3. Calculate the average monthly revenue
Show the code and results.""",
    config=types.GenerateContentConfig(
        tools=[types.Tool(code_execution=types.ToolCodeExecution())]
    )
)

for part in response.candidates[0].content.parts:
    if part.executable_code:
        print("💻 CODE:")
        print(part.executable_code.code)
        print()
    elif part.code_execution_result:
        print("📊 OUTPUT:")
        print(part.code_execution_result.output)
        print()
    elif part.text:
        print("📝", part.text)

"""### 3.5 Function Calling

Function calling transforms LLMs into systems that interact with external tools and APIs.  
You define functions, and the model decides when and how to call them.
"""

# --- Function Calling: Weather example ---

# Step 1: Define the function declaration (schema for the model)
get_weather_func = types.FunctionDeclaration(
    name="get_weather",
    description="Get the current weather for a given city",
    parameters=types.Schema(
        type="OBJECT",
        properties={
            "city": types.Schema(type="STRING", description="The city name"),
            "unit": types.Schema(type="STRING", enum=["celsius", "fahrenheit"], description="Temperature unit"),
        },
        required=["city"],
    ),
)

# Step 2: Send user query with the tool
response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="What's the weather like in Hanoi today?",
    config=types.GenerateContentConfig(
        tools=[types.Tool(function_declarations=[get_weather_func])]
    )
)

# Step 3: The model returns a function call (not the result!)
function_call = response.candidates[0].content.parts[0].function_call
print(f"🔧 Model wants to call: {function_call.name}")
print(f"   With args: {dict(function_call.args)}")

# Step 4: Simulate the function execution & send result back

# In a real app, you'd call your actual weather API here
fake_weather_result = {"temperature": 28, "condition": "Partly cloudy", "humidity": 75}

# Build the conversation: reuse the model's actual response, then append the function result
followup_response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents=[
        # Original user message
        types.Content(role="user", parts=[types.Part.from_text(text="What's the weather like in Hanoi today?")]),
        # Model's response (reuse directly — it contains the function_call part)
        response.candidates[0].content,
        # Your function result fed back as a "user" turn
        types.Content(role="user", parts=[types.Part.from_function_response(
            name=function_call.name,
            response=fake_weather_result
        )]),
    ],
    config=types.GenerateContentConfig(
        tools=[types.Tool(function_declarations=[get_weather_func])]
    )
)

print("🤖", followup_response.text)

"""### 3.6 File Search (RAG)

Upload documents and let Gemini retrieve relevant chunks to answer questions.
"""

# --- File Search: Upload a file and ask questions about it ---
# NOTE: This creates server-side resources. Clean up after!

import tempfile

# Create a sample document
sample_text = """Obello Design Inc. AI Product Roadmap 2026

AI Resize: Automatically resize designs for multiple platforms.
Phase 1 focuses on simple layouts. Phase 2 handles complex multi-element designs.

Design Copilot: AI assistant that suggests design improvements in real-time.
Uses a combination of CNN-based evaluation and LLM reasoning.

AI Remix: Transform existing designs into new styles while preserving brand identity.
Leverages few-shot prompting and style transfer techniques.

Brand Voice: Ensures all generated content matches the brand's tone and style.
Built on fine-tuned language models with brand-specific training data.
"""

with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
    f.write(sample_text)
    temp_path = f.name

# Create a file search store
file_search_store = client.file_search_stores.create(
    config={'display_name': 'workshop-demo-store'}
)
print(f"✅ Created store: {file_search_store.name}")

# Upload the file
operation = client.file_search_stores.upload_to_file_search_store(
    file=temp_path,
    file_search_store_name=file_search_store.name,
    config={'display_name': 'product-roadmap.txt'}
)
print(f"✅ File uploaded")

# Query the uploaded document
import time
time.sleep(5)  # Wait for indexing

response = client.models.generate_content(
    model="gemini-3-flash-preview",
    contents="What AI products are on the roadmap and what technologies do they use?",
    config=types.GenerateContentConfig(
        tools=[
            types.Tool(
                file_search=types.FileSearch(
                    file_search_store_names=[file_search_store.name]
                )
            )
        ]
    )
)

print(response.text)

# Cleanup: Delete the file search store
try:
    client.file_search_stores.delete(name=file_search_store.name)
    print("🗑️ Store deleted")
except Exception as e:
    print(f"Cleanup note: {e}")

os.unlink(temp_path)
print("🗑️ Temp file deleted")

"""---
## 4. GenMedia — Image Generation

### Nano Banana Pro (in Gemini 3 Pro)
- State-of-the-art text rendering in images
- Precision controls & reference images
- Best for complex, sophisticated outputs

### Nano Banana (in Gemini 2.5 Flash)
- Fast, conversational editing (10-15s)
- Character consistency, local edits
"""

# --- Image Generation with Nano Banana (Gemini 2.5 Flash) ---

from IPython.display import display, Image as IPImage
from PIL import Image
import io
import base64

response = client.models.generate_content(
    model="gemini-2.5-flash-image",
    contents="Generate an image of a cute robot mascot for an AI design startup, in a modern flat illustration style with vibrant colors.",
    config=types.GenerateContentConfig(
        response_modalities=["TEXT", "IMAGE"]
    )
)

# Display results
for part in response.candidates[0].content.parts:
    if part.text:
        print(part.text)
    elif part.inline_data:
        img_data = part.inline_data.data
        img = Image.open(io.BytesIO(img_data))
        img.save("generated_image.png")
        display(IPImage(data=img_data))
        print("\n✅ Image saved to generated_image.png")

# --- Nano Banana Pro: Advanced text rendering ---

response = client.models.generate_content(
    model="gemini-3-pro-image-preview",
    contents="""Create a professional event badge design with:
- Title: "GDGoC UTM 2026"
- Subtitle: "Building Responsible AI"
- Clean modern design with blue and white colors, with name of Ms. Linh Nguyen""",
    config=types.GenerateContentConfig(
        response_modalities=["TEXT", "IMAGE"]
    )
)

for part in response.candidates[0].content.parts:
    if part.text:
        print(part.text)
    elif part.inline_data:
        img_data = part.inline_data.data
        img = Image.open(io.BytesIO(img_data))
        img.save("badge_design.png")
        display(IPImage(data=img_data))
        print("\n✅ Image saved to badge_design.png")

"""### Imagen 4 — Standalone Image Generation"""

# --- Imagen 4: High-quality image generation ---

response = client.models.generate_images(
    model="imagen-4.0-generate-001",
    prompt="A serene Japanese zen garden with cherry blossoms, koi pond, and stone lantern, golden hour lighting, photorealistic",
    config=types.GenerateImagesConfig(
        number_of_images=1,
    )
)

for image in response.generated_images:
    img = Image.open(io.BytesIO(image.image.image_bytes))
    img.save("imagen4_output.png")
    display(IPImage(data=image.image.image_bytes))
    print("✅ Imagen 4 image saved")

"""---
## 5. Audio & Speech

### Text-to-Speech (TTS)
- 2 TTS models: Pro and Flash
- Controllable emotion and style
- Multi-voice conversations
- Ideal for podcasts, audiobooks, customer support
"""

# --- Text-to-Speech with Gemini ---

import wave
from IPython.display import Audio

response = client.models.generate_content(
    model="gemini-2.5-flash-preview-tts",
    contents="Welcome to the Gemini API workshop! Today we'll explore the amazing capabilities of Google's AI models.",
    config=types.GenerateContentConfig(
        response_modalities=["AUDIO"],
        speech_config=types.SpeechConfig(
            voice_config=types.VoiceConfig(
                prebuilt_voice_config=types.PrebuiltVoiceConfig(
                    voice_name="Kore"  # Try: Puck, Charon, Kore, Fenrir, Aoede, Leda, Orus, Zephyr
                )
            )
        ),
    ),
)

# Save and play the audio
audio_data = response.candidates[0].content.parts[0].inline_data.data

with wave.open("tts_output.wav", "wb") as wf:
    wf.setnchannels(1)
    wf.setsampwidth(2)
    wf.setframerate(24000)
    wf.writeframes(audio_data)

print("✅ Audio saved to tts_output.wav")
Audio("tts_output.wav")

# --- Multi-voice TTS: Podcast-style dialog ---

response = client.models.generate_content(
    model="gemini-2.5-flash-preview-tts",
    contents="""Generate a short podcast dialog between two speakers:

Speaker 1 (Kore): Hi everyone, welcome to AI Weekly! I'm excited about today's topic.
Speaker 2 (Puck): Me too! We're covering the latest Gemini 3 release from Google.
Speaker 1 (Kore): That's right. The big theme is shifting from thinking to action.
Speaker 2 (Puck): And the benchmarks are really impressive. Let's dive in!""",
    config=types.GenerateContentConfig(
        response_modalities=["AUDIO"],
        speech_config=types.SpeechConfig(
            multi_speaker_voice_config=types.MultiSpeakerVoiceConfig(
                speaker_voice_configs=[
                    types.SpeakerVoiceConfig(speaker="Speaker 1", voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name="Kore")
                    )),
                    types.SpeakerVoiceConfig(speaker="Speaker 2", voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name="Puck")
                    )),
                ]
            )
        ),
    ),
)

audio_data = response.candidates[0].content.parts[0].inline_data.data

with wave.open("podcast_output.wav", "wb") as wf:
    wf.setnchannels(1)
    wf.setsampwidth(2)
    wf.setframerate(24000)
    wf.writeframes(audio_data)

print("✅ Podcast audio saved to podcast_output.wav")
Audio("podcast_output.wav")

"""---
## 7. Bonus: Agent Frameworks

Gemini works with all major agent frameworks. Here are quick-start snippets.
"""

# --- Google ADK (Agent Development Kit) ---

from google.adk.agents import Agent
from google.adk.tools import google_search
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
import os
os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

# Create the agent
search_agent = Agent(
    name="search_assistant",
    model="gemini-3-flash-preview",
    instruction="""You are a helpful research assistant.
    Use Google Search to find current, accurate information.
    Always cite your sources.""",
    tools=[google_search]
)

# Set up runner
session_service = InMemorySessionService()
runner = Runner(agent=search_agent, app_name="workshop", session_service=session_service)

# Create session and run
session = await session_service.create_session(app_name="workshop", user_id="user1")

from google.genai import types as genai_types


async for event in runner.run_async(
    user_id="user1",
    session_id=session.id,
    new_message=genai_types.Content(
        role="user",
        parts=[genai_types.Part.from_text(text="What are the top 3 AI breakthroughs in 2025?")]
    )
):
    if event.is_final_response() and event.content and event.content.parts:
        print("🤖", event.content.parts[0].text)

# --- LangChain / LangGraph ---
!pip install -q langchain-google-genai langgraph langchain-core langchain-community

# --- LangChain + LangGraph: ReAct Agent with Tools ---

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent

# Init the LLM
llm = ChatGoogleGenerativeAI(
    model="gemini-3-flash-preview",
    google_api_key=GOOGLE_API_KEY,
    temperature=0.7,
)

# Define custom tools
@tool
def calculate(expression: str) -> str:
    """Evaluate a math expression. Example: '2 + 3 * 4'"""
    try:
        result = eval(expression, {"__builtins__": {}}, {})
        return str(result)
    except Exception as e:
        return f"Error: {e}"

@tool
def get_company_info(company_name: str) -> str:
    """Get information about a company's AI products."""
    db = {
        "google": "Google develops Gemini models (3 Pro, 3 Flash), Imagen 4, Veo 3, and tools like AI Studio, ADK, and the Live API.",
        "anthropic": "Anthropic develops Claude models (Opus, Sonnet, Haiku) focused on AI safety and helpfulness.",
        "openai": "OpenAI develops GPT models, DALL-E for images, Whisper for speech, and the ChatGPT platform.",
        "meta": "Meta develops LLaMA open-source models and is integrating AI across Facebook, Instagram, and WhatsApp.",
    }
    return db.get(company_name.lower(), f"No info found for {company_name}")

# Create the ReAct agent
agent = create_react_agent(llm, tools=[calculate, get_company_info])

# Run it
result = await agent.ainvoke({
    "messages": [{"role": "user", "content": "Compare Google and Anthropic's AI products. Also, what's 1.5 billion divided by 7 million?"}]
})

# Print conversation
for msg in result["messages"]:
    role = msg.__class__.__name__
    if role == "AIMessage" and msg.content:
        print(f"🤖 Agent: {msg.content}\n")
    elif role == "ToolMessage":
        print(f"🔧 Tool [{msg.name}]: {msg.content}")

!pip install -q crewai crewai-tools

# --- CrewAI: Multi-Agent Research Team ---

from crewai import LLM, Agent, Task, Crew, Process

# Gemini LLM
llm = LLM(
    model="gemini/gemini-3-flash-preview",
    api_key=GOOGLE_API_KEY,
    temperature=0.7,
)

# Define specialized agents
researcher = Agent(
    role="AI Research Analyst",
    goal="Research and analyze the latest AI model landscape",
    backstory="You are a senior AI analyst who tracks model releases and benchmarks across Google, Anthropic, OpenAI, and Meta.",
    llm=llm,
    verbose=True,
)

writer = Agent(
    role="Technical Writer",
    goal="Create clear, concise summaries for a technical audience",
    backstory="You are a technical writer at a startup who translates complex AI research into actionable insights for the engineering team.",
    llm=llm,
    verbose=True,
)

# Define tasks
research_task = Task(
    description="""Analyze the current state of frontier AI models in late 2025.
    Cover: Gemini 3, Claude 4, GPT-5, and LLaMA 4.
    Focus on: key capabilities, benchmark performance, and pricing tiers.
    Use your knowledge to provide a comprehensive overview.""",
    expected_output="A structured analysis of 4 frontier AI models with capabilities, benchmarks, and pricing.",
    agent=researcher,
)

summary_task = Task(
    description="""Based on the research analysis, write a concise executive briefing
    (max 300 words) for the Head of AI at a design startup called Obello.
    Focus on which models are most relevant for:
    1. AI-powered image generation and editing
    2. Layout understanding and resizing
    3. Agentic coding workflows
    Recommend the top 2 models to prioritize.""",
    expected_output="A 300-word executive briefing with model recommendations for Obello's AI team.",
    agent=writer,
)

# Assemble and run the crew
crew = Crew(
    agents=[researcher, writer],
    tasks=[research_task, summary_task],
    process=Process.sequential,
    verbose=True,
)

result = crew.kickoff()
print("\n" + "="*60)
print("📋 FINAL BRIEFING:")
print("="*60)
print(result.raw)

!pip install -q llama-index-llms-google-genai llama-index-core

# --- LlamaIndex: Agent with Tools ---


from llama_index.llms.google_genai import GoogleGenAI
from llama_index.core.agent.workflow import AgentWorkflow, FunctionAgent
from llama_index.core.tools import FunctionTool

# Init LLM
llm = GoogleGenAI(
    model="gemini-3-flash-preview",
    api_key=GOOGLE_API_KEY,
)

# Define tools as plain functions
def analyze_design_complexity(description: str) -> str:
    """Analyze the complexity tier of a design layout for AI resizing.

    Args:
        description: A text description of the design layout.
    """
    keywords_complex = ["overlapping", "multi-layer", "bleed", "rotation", "gradient mask"]
    keywords_medium = ["grid", "columns", "sidebar", "header-footer", "nested"]

    desc_lower = description.lower()
    complex_hits = sum(1 for k in keywords_complex if k in desc_lower)
    medium_hits = sum(1 for k in keywords_medium if k in desc_lower)

    if complex_hits >= 2:
        tier = "Tier 3 (Complex)"
        approach = "Use LayoutGAN++ with constraint-based resizing and manual QA pass."
    elif medium_hits >= 2 or complex_hits >= 1:
        tier = "Tier 2 (Medium)"
        approach = "Use CNN-based evaluation with few-shot prompting for layout adjustment."
    else:
        tier = "Tier 1 (Simple)"
        approach = "Use rule-based resizing with aspect ratio preservation."

    return f"Complexity: {tier}\nRecommended approach: {approach}\nComplex signals: {complex_hits}, Medium signals: {medium_hits}"


def estimate_resize_time(num_elements: int, tier: str) -> str:
    """Estimate processing time for AI resize based on element count and complexity tier.

    Args:
        num_elements: Number of design elements in the layout.
        tier: Complexity tier (1, 2, or 3).
    """
    base_times = {"1": 0.5, "2": 2.0, "3": 5.0}
    base = base_times.get(str(tier), 2.0)
    total = base + (num_elements * 0.1)
    return f"Estimated processing time: {total:.1f} seconds for {num_elements} elements at Tier {tier}"


# Wrap as LlamaIndex tools
complexity_tool = FunctionTool.from_defaults(fn=analyze_design_complexity)
time_tool = FunctionTool.from_defaults(fn=estimate_resize_time)

# Create agent
agent = FunctionAgent(
    name="design_analyst",
    description="Analyzes design layouts for AI resize complexity and estimates processing time.",
    llm=llm,
    tools=[complexity_tool, time_tool],
    system_prompt="""You are an AI design analysis assistant for Obello Design Inc.
    When given a design description, first analyze its complexity tier,
    then estimate processing time. Provide actionable recommendations.""",
)

workflow = AgentWorkflow(agents=[agent])

# Run
response = await workflow.run(
    user_msg="""Analyze this design for AI resize:
    A marketing banner with overlapping text layers, a gradient mask background,
    sidebar with 3 columns of product cards, and a header-footer with logo.
    It has approximately 24 elements total."""
)

print("🤖", response)

"""---
## 📚 Resources

| Resource | Link |
|----------|------|
| Google AI Studio | [aistudio.google.com](https://aistudio.google.com) |
| Gemini API Docs | [ai.google.dev/gemini-api](https://ai.google.dev/gemini-api) |
| Cookbook (code examples) | [goo.gle/cookbook](https://goo.gle/cookbook) |
| ADK Docs | [google.github.io/adk-docs](https://google.github.io/adk-docs/) |
| ADK Streaming | [google.github.io/adk-docs/streaming](https://google.github.io/adk-docs/streaming/) |
| Lyria RealTime | [goo.gle/lyria-realtime](https://goo.gle/lyria-realtime) |

---

**Happy building!** 🚀
"""